### ISSUE TITLE
Does not update Background img

### ISSUE THREAD

**Issue by Goblinmine** [Nriver/bing-daily-theme#1]
I put the theme folder into my **hidden** root object. that causes the `UpdateWallpaper.js` not to find the main theme file with ``api.searchForNote(`#BingDailyNote`);``

**Comment by Nriver** [comment]
What does the `hidden` mean?

**Comment by Goblinmine** [comment]
there is the main root object:
![image](https://github.com/user-attachments/assets/c1392649-5df1-4070-9e63-56f103036b62)
And if you search for `hidden` you can find a hidden object / path:
![image](https://github.com/user-attachments/assets/eefc895f-db7d-4ac4-b9c1-105ebeb803ac)

**Comment by Nriver** [comment]
Did you refer to the `Hidden Notes` in `Show Hidden Subtree` ? You are not supposed to put your notes there. I would suggest you move them out from that.

**Comment by Goblinmine** [comment]
It should be fine tho if i dont change anything that is already in there and just make myself a new folder that is directly under the **Hidden notes** object. 😭

I did that bc. i dont want to see my themes folder xD. Is there maybe another way to make them invisible?

**Comment by Nriver** [comment]
I don't believe it's feasible in the current version. If you're keen on the feature, consider reaching out to the community at https://github.com/orgs/TriliumNext/discussions to explore if anyone can help bring this idea to life.

**Comment by Goblinmine** [comment]
So no fix because its not supposed to be in there?

I still don't quite understand what exactly the problem is with having my own folder in the `Hidden Notes Subtree`.

**Comment by Nriver** [comment]
It's designed in that way. The notes under the hidden note are managed by the program. If I try to add a new sub note under the hidden note root. This error message would show up `Creating child notes into '_hidden' is not allowed.`

**Comment by Goblinmine** [comment]
I see. i never even got that error msg because it's missing for copying/moving folders into this `_hidden` folder. So i thought it was fine.. because it didn't break anything and worked like normal
